[package]
name = "windmesser"
version = "0.1.0"
authors = ["Markus Diewald <mdiewald@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.1.10"
sysfs_gpio = "0.5.4"
chrono = "0.4.9"
